Broker Id Hostvar
ansible-middleware/amq_streams pull request #98
Opened 2023-10-09 20:12 UTC by gbaufake

- Modifies the broker.id on a template to allow hostvar if it is defined.
- Closes https://github.com/ansible-middleware/amq_streams/issues/82

2023-10-10 05:59 UTC, rmarting requested changes
@gbaufake Just a comment to improve this PR (before a better revision of @rpelisse):

* The variables for a role should start with the name of the role (e.g: `amq_streams_broker_XXX`)
* It is important to document the variable, default values, and scope to help its use (adding an example is much appreciated)

Thanks your contribution!

2023-10-10 19:08 UTC, gbaufake commented
@rpelisse and @rmarting Submitted the changes.

2023-10-11 06:04 UTC, rmarting commented
LGTM! @rpelisse your turn :wink:

2023-10-11 06:58 UTC, rpelisse approved these changes
LGTM!

2023-10-12 14:33 UTC, merged