Add custom zookeeper_id for each host based in inventory
ansible-middleware/amq_streams pull request #99
Opened 2023-10-09 20:37 UTC by gbaufake

- Modifies the zookeeper_id  on a template to allow hostvar if it is defined. If it is not specified, it uses the standard indexing from the template.
- Closes https://github.com/ansible-middleware/amq_streams/issues/81

2023-10-10 05:58 UTC, rmarting commented
@gbaufake Just a comment to improve this PR (before a better revision of @rpelisse):

* The variables for a role should start with the name of the role (e.g: `amq_streams_zookeeper_XXX`)
* It is important to document the variable, default values, and scope to help its use (adding an example is much appreciated)

Thanks your contribution!

2023-10-10 05:58 UTC, rmarting requested changes
Could you review our comments? Thanks

2023-10-10 15:48 UTC, rpelisse requested changes
Can you please update your PR following Roman's feedback? :)

2023-10-12 11:45 UTC, rpelisse approved these changes

2023-10-12 14:33 UTC, merged